In [2]:
import requests
import pandas as pd

In [5]:

CNPJ_PE = "10571982000125"
url = "https://api.transferegov.gestao.gov.br/transferenciasespeciais/plano_acao_especial"
params = {
    "cnpj_beneficiario_plano_acao": f"eq.{CNPJ_PE}"
}
response = requests.get(url, params=params)
dados = response.json()

# Se a resposta for uma lista de dicts:
df_planos_pe_2020 = pd.DataFrame(dados)
display(df_planos_pe_2020.head(20))

,id_plano_acao,codigo_plano_acao,ano_plano_acao,modalidade_plano_acao,situacao_plano_acao,cnpj_beneficiario_plano_acao,nome_beneficiario_plano_acao,uf_beneficiario_plano_acao,codigo_banco_plano_acao,codigo_situacao_dado_bancario_plano_acao,...,codigo_parlamentar_emenda_plano_acao,sequencial_emenda_parlamentar_plano_acao,numero_emenda_parlamentar_plano_acao,codigo_emenda_parlamentar_formatado_plano_acao,codigo_descricao_areas_politicas_publicas_plano_acao,descricao_programacao_orcamentaria_plano_acao,motivo_impedimento_plano_acao,valor_custeio_plano_acao,valor_investimento_plano_acao,id_programa
0,9904,09032021-009904,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,2534,5,202125340005,202125340005-Paulo Teixeira,26-Transporte / 782-Transporte Rodoviário,None,None,180000.0,0.0,5
1,10094,09032021-010094,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,2718,14,202127180014,202127180014-Augusto Coutinho,26-Transporte / 782-Transporte Rodoviário,0465.4134.A170,None,0.0,500000.0,5
2,10588,09032021-010588,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,2885,9,202128850009,202128850009-Humberto Costa,"12-Educação / 361-Ensino Fundamental , 12-Educ...",Ação 4072 - Manutenção,None,45000.0,105000.0,5
3,10589,09032021-010589,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,2885,14,202128850014,202128850014-Humberto Costa,"12-Educação / 361-Ensino Fundamental , 18-Gest...",4620-FORTALECIMENTO AMBIENTAL DO ESTADO DE PER...,None,150000.0,350000.0,5
4,11064,09032021-011064,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3387,2,202133870002,202133870002-Wolney Queiroz,26-Transporte / 782-Transporte Rodoviário,26.782.04565.4134.A170,None,0.0,2000000.0,5
5,11438,09032021-011438,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3767,6,202137670006,202137670006-Tadeu Alencar,14-Direitos da Cidadania / 422-Direitos Indivi...,14-Direitos da Cidadania / 422-Direitos Indivi...,None,100000.0,390000.0,5
6,11439,09032021-011439,2021,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3767,15,202137670015,202137670015-Tadeu Alencar,8-Assistência Social / 243-Assistência à Crian...,"R$ 30.000,00 AQUISIÇÃO EQUIPAMENTOS E R$ 70.00...",None,30000.0,70000.0,5
7,15240,09032022-015240,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,4213,20,202242130020,202242130020-Milton Coelho,"12-Educação / 362-Ensino Médio , 13-Cultura / ...",Ação 0493 - Apoio às ações de Divulgação e à E...,None,700000.0,530000.0,7
8,15962,09032022-015962,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,1690,3,202216900003,202216900003-Renildo Calheiros,"13-Cultura / 391-Patrimônio Histórico, Artísti...",13.391.0929.4724,None,0.0,352000.0,7
9,16106,09032022-016106,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3767,9,202237670009,202237670009-Tadeu Alencar,"13-Cultura / 391-Patrimônio Histórico, Artísti...",13.391.0929.4724,None,353700.0,1275982.0,7
10,16630,09032022-016630,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,2885,20,202228850020,202228850020-Humberto Costa,"12-Educação / 364-Ensino Superior , 13-Cultura...",12.571.0069.4739.2998,None,150000.0,350000.0,7
11,16846,09032022-016846,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,1218,1,202212180001,202212180001-Gonzaga Patriota,8-Assistência Social / 243-Assistência à Crian...,1030 - Melhoria da Infraestrutura Hídrica no M...,None,100000.0,603365.0,7
12,17895,09032022-017895,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,2718,7,202227180007,202227180007-Augusto Coutinho,"12-Educação / 362-Ensino Médio , 20-Agricultur...",1022 - Inclusão Produtiva das Trabalhadoras e ...,None,0.0,700000.0,7
13,18765,09032022-018765,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3187,4,202231870004,202231870004-Felipe Carreras,12-Educação / 362-Ensino Médio,Ação 3314 - Aquisição de Kit Escola Conectada...,None,0.0,198453.0,7
14,18953,09032022-018953,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3387,3,202233870003,202233870003-Wolney Queiroz,26-Transporte / 782-Transporte Rodoviário,26.782.0465.4134.A170,None,0.0,3000000.0,7
15,19391,09032022-019391,2022,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3767,8,202237670008,202237670008-Tadeu Alencar,"13-Cultura / 391-Patrimônio Histórico, Artísti...",13.391.0929.4326.4724,None,0.0,500000.0,7
16,35728,09032023-035728,2023,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3080,1,202330800001,202330800001-Daniel Coelho,23-Comércio e Serviços / 695-Turismo,4142- Expansão e Qualificação de Equipamentos ...,None,0.0,15551700.0,12
17,36482,09032023-036482,2023,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3767,7,202337670007,202337670007-Tadeu Alencar,8-Assistência Social / 243-Assistência à Crian...,1161- Estruturação da rede SUAS no Estado de P...,None,0.0,100000.0,12
18,70415,09032024-070415,2024,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,4252,6,202442520006,202442520006-Fernando Dueire,"13-Cultura / 391-Patrimônio Histórico, Artísti...",None,None,300000.0,0.0,21
19,72783,09032024-072783,2024,Especial,CIENTE,10571982000125,ESTADO DE PERNAMBUCO,PE,104,4,...,3931,1,202439310001,202439310001-Carlos Veras,12-Educação / 364-Ensino Superior,None,None,0.0,1000000.0,21

In [6]:
ids_planos_pe_2020 = df_planos_pe_2020['id_plano_acao']

print(ids_planos_pe_2020.head(20))

0      9904
1     10094
2     10588
3     10589
4     11064
5     11438
6     11439
7     15240
8     15962
9     16106
10    16630
11    16846
12    17895
13    18765
14    18953
15    19391
16    35728
17    36482
18    70415
19    72783
Name: id_plano_acao, dtype: int64

In [7]:
# Supondo que ids_planos_pe_2020 seja uma lista de inteiros ou strings
ids_str = ",".join(str(i) for i in ids_planos_pe_2020)
url = "https://api.transferegov.gestao.gov.br/transferenciasespeciais/plano_trabalho_especial"
params = {
    "id_plano_acao": f"in.({ids_str})"
}
response = requests.get(url, params=params)
dados = response.json()

if isinstance(dados, list):
    df_planos_trabalho_pe_2020 = pd.DataFrame(dados)
else:
    print("Resposta inesperada:", dados)
    df_planos_trabalho_pe_2020 = pd.DataFrame()
display(df_planos_trabalho_pe_2020.head(20))

,id_plano_trabalho,situacao_plano_trabalho,ind_orcamento_proprio_plano_trabalho,data_inicio_execucao_plano_trabalho,data_fim_execucao_plano_trabalho,prazo_execucao_meses_plano_trabalho,id_plano_acao,classificacao_orcamentaria_pt,ind_justificativa_prorrogacao_atraso_pt,ind_justificativa_prorrogacao_paralizacao_pt,justificativa_prorrogacao_pt
0,20393,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,9904,26.782.0465.4134.A170,False,False,
1,19592,Enviado para Análise,Sim,2024-12-13T00:00:00,2025-12-13T00:00:00,12,70415,FUNCIONAL PROGRAMÁTICA: 28. 845.0903.0EC2.,False,False,
2,20535,APROVADO,Sim,2023-08-30T00:00:00,2028-08-30T00:00:00,60,35728,Ação 4142 e Subação 2499.\n\n,False,False,
3,21165,Em Complementação,Sim,2022-07-01T00:00:00,2024-07-01T00:00:00,24,15962,13.391.0929.4724,False,False,
4,21060,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,10588,Ação 4072.0000 manutenção\nAção 3314.0000 Aqui...,False,False,
5,20700,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,11438,26.782.4134.A170 \n13.391.0929.4724.2125\n14 4...,False,False,
6,20898,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,11439,Fone 0660 - GND3 e GND4,False,False,
7,5259,Enviado para Análise,Sim,2024-07-03T00:00:00,2027-07-03T00:00:00,36,72783,Programa de trabalho: ...,False,False,
8,20550,Enviado para Análise,Sim,2022-07-01T00:00:00,2025-07-01T00:00:00,36,15240,SECULT = Subação: 13.392.0370.1718.EMWS - Ampl...,False,False,
9,20602,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,10589,26.782.0465.4134.A170 - DER\n18.541.0478.4620....,False,False,
10,20724,Enviado para Análise,Sim,2023-03-29T00:00:00,2026-03-29T00:00:00,36,16846,4055 - Ampliação da Infraestrutura e dos Servi...,False,False,
11,21138,Enviado para Análise,Sim,2022-07-01T00:00:00,2024-07-01T00:00:00,24,19391,13.391.0929.4724,False,False,
12,20761,Enviado para Análise,Sim,2022-07-01T00:00:00,2025-07-01T00:00:00,36,17895,4145 - Fomento à Atividade Agropecuária e ao F...,False,False,
13,20715,Enviado para Análise,Sim,2022-07-01T00:00:00,2026-07-01T00:00:00,48,18953,26.782.0465.4134.A170,False,False,
14,21004,Enviado para Análise,Sim,2022-07-01T00:00:00,2025-07-01T00:00:00,36,18765,Ação 3314.0000,False,False,
15,21161,Enviado para Análise,Sim,2023-03-29T00:00:00,2025-03-29T00:00:00,24,16106,13.391.0929.4724,False,False,
16,20540,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,10094,26.782.0465.4134.A170,False,False,
17,20190,Enviado para Análise,Sim,2023-03-29T00:00:00,2026-03-29T00:00:00,36,16630,PROGRAMA DE TRABALHO 12.571.0069.4739.2998 - P...,False,False,
18,20640,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,11064,26.782.0465.A170,False,False,
19,20984,Enviado para Análise,Não,2023-08-30T00:00:00,2026-08-30T00:00:00,36,36482,,False,False,

In [4]:
df_planos_pe_2020.to_excel("../excel_with_filter/2020_notebooks/planos_acao_especial_PE_2020.xlsx", index=False)
df_planos_trabalho_pe_2020.to_excel("../excel_with_filter/2020_notebooks/planos_trabalho_especial_PE_2020.xlsx", index=False)

In [5]:
df_planos_pe_2020.to_csv("../csv_with_filter/planos_acao_especial_PE_2020.xlsx", index=False)
df_planos_trabalho_pe_2020.to_csv("../csv_with_filter/planos_trabalho_especial_PE_2020.xlsx", index=False)

In [11]:
# Carregue os arquivos Excel
df_planos = pd.read_excel("../excel_with_filter/2020_notebooks/planos_acao_especial_PE_2020.xlsx")
df_planos_trabalho = pd.read_excel("../excel_with_filter/2020_notebooks/planos_trabalho_especial_PE_2020.xlsx")

# Faça o merge pelo campo em comum (ajuste se o nome da coluna for diferente)
df_merged = df_planos_trabalho.merge(
    df_planos,
    on="id_plano_acao",
    how="left",
    suffixes=('_trabalho', '_plano')
)

# Exporte o resultado
df_merged.to_excel("../excel_with_filter/2020_notebooks/planos_trabalho_completo_PE_2020.xlsx", index=False)

In [12]:
display(df_merged.head(20))

,id_plano_trabalho,situacao_plano_trabalho,ind_orcamento_proprio_plano_trabalho,data_inicio_execucao_plano_trabalho,data_fim_execucao_plano_trabalho,prazo_execucao_meses_plano_trabalho,id_plano_acao,classificacao_orcamentaria_pt,ind_justificativa_prorrogacao_atraso_pt,ind_justificativa_prorrogacao_paralizacao_pt,...,codigo_parlamentar_emenda_plano_acao,sequencial_emenda_parlamentar_plano_acao,numero_emenda_parlamentar_plano_acao,codigo_emenda_parlamentar_formatado_plano_acao,codigo_descricao_areas_politicas_publicas_plano_acao,descricao_programacao_orcamentaria_plano_acao,motivo_impedimento_plano_acao,valor_custeio_plano_acao,valor_investimento_plano_acao,id_programa
0,20393,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,9904,26.782.0465.4134.A170,False,False,...,2534,5,202125340005,202125340005-Paulo Teixeira,26-Transporte / 782-Transporte Rodoviário,NaN,NaN,180000,0,5
1,19592,Enviado para Análise,Sim,2024-12-13T00:00:00,2025-12-13T00:00:00,12,70415,FUNCIONAL PROGRAMÁTICA: 28. 845.0903.0EC2.,False,False,...,4252,6,202442520006,202442520006-Fernando Dueire,"13-Cultura / 391-Patrimônio Histórico, Artísti...",NaN,NaN,300000,0,21
2,20535,APROVADO,Sim,2023-08-30T00:00:00,2028-08-30T00:00:00,60,35728,Ação 4142 e Subação 2499.\n\n,False,False,...,3080,1,202330800001,202330800001-Daniel Coelho,23-Comércio e Serviços / 695-Turismo,4142- Expansão e Qualificação de Equipamentos ...,NaN,0,15551700,12
3,21060,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,10588,Ação 4072.0000 manutenção\nAção 3314.0000 Aqui...,False,False,...,2885,9,202128850009,202128850009-Humberto Costa,"12-Educação / 361-Ensino Fundamental , 12-Educ...",Ação 4072 - Manutenção,NaN,45000,105000,5
4,20700,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,11438,26.782.4134.A170 \n13.391.0929.4724.2125\n14 4...,False,False,...,3767,6,202137670006,202137670006-Tadeu Alencar,14-Direitos da Cidadania / 422-Direitos Indivi...,14-Direitos da Cidadania / 422-Direitos Indivi...,NaN,100000,390000,5
5,20898,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,11439,Fone 0660 - GND3 e GND4,False,False,...,3767,15,202137670015,202137670015-Tadeu Alencar,8-Assistência Social / 243-Assistência à Crian...,"R$ 30.000,00 AQUISIÇÃO EQUIPAMENTOS E R$ 70.00...",NaN,30000,70000,5
6,5259,Enviado para Análise,Sim,2024-07-03T00:00:00,2027-07-03T00:00:00,36,72783,Programa de trabalho: ...,False,False,...,3931,1,202439310001,202439310001-Carlos Veras,12-Educação / 364-Ensino Superior,NaN,NaN,0,1000000,21
7,20550,Enviado para Análise,Sim,2022-07-01T00:00:00,2025-07-01T00:00:00,36,15240,SECULT = Subação: 13.392.0370.1718.EMWS - Ampl...,False,False,...,4213,20,202242130020,202242130020-Milton Coelho,"12-Educação / 362-Ensino Médio , 13-Cultura / ...",Ação 0493 - Apoio às ações de Divulgação e à E...,NaN,700000,530000,7
8,20602,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,10589,26.782.0465.4134.A170 - DER\n18.541.0478.4620....,False,False,...,2885,14,202128850014,202128850014-Humberto Costa,"12-Educação / 361-Ensino Fundamental , 18-Gest...",4620-FORTALECIMENTO AMBIENTAL DO ESTADO DE PER...,NaN,150000,350000,5
9,20724,Enviado para Análise,Sim,2023-03-29T00:00:00,2026-03-29T00:00:00,36,16846,4055 - Ampliação da Infraestrutura e dos Servi...,False,False,...,1218,1,202212180001,202212180001-Gonzaga Patriota,8-Assistência Social / 243-Assistência à Crian...,1030 - Melhoria da Infraestrutura Hídrica no M...,NaN,100000,603365,7
10,21138,Enviado para Análise,Sim,2022-07-01T00:00:00,2024-07-01T00:00:00,24,19391,13.391.0929.4724,False,False,...,3767,8,202237670008,202237670008-Tadeu Alencar,"13-Cultura / 391-Patrimônio Histórico, Artísti...",13.391.0929.4326.4724,NaN,0,500000,7
11,20761,Enviado para Análise,Sim,2022-07-01T00:00:00,2025-07-01T00:00:00,36,17895,4145 - Fomento à Atividade Agropecuária e ao F...,False,False,...,2718,7,202227180007,202227180007-Augusto Coutinho,"12-Educação / 362-Ensino Médio , 20-Agricultur...",1022 - Inclusão Produtiva das Trabalhadoras e ...,NaN,0,700000,7
12,20715,Enviado para Análise,Sim,2022-07-01T00:00:00,2026-07-01T00:00:00,48,18953,26.782.0465.4134.A170,False,False,...,3387,3,202233870003,202233870003-Wolney Queiroz,26-Transporte / 782-Transporte Rodoviário,26.782.0465.4134.A170,NaN,0,3000000,7
13,21004,Enviado para Análise,Sim,2022-07-01T00:00:00,2025-07-01T00:00:00,36,18765,Ação 3314.0000,False,False,...,3187,4,202231870004,202231870004-Felipe Carreras,12-Educação / 362-Ensino Médio,Ação 3314 - Aquisição de Kit Escola Conectada...,NaN,0,198453,7
14,21161,Enviado para Análise,Sim,2023-03-29T00:00:00,2025-03-29T00:00:00,24,16106,13.391.0929.4724,False,False,...,3767,9,202237670009,202237670009-Tadeu Alencar,"13-Cultura / 391-Patrimônio Histórico, Artísti...",13.391.0929.4724,NaN,353700,1275982,7
15,20540,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,10094,26.782.0465.4134.A170,False,False,...,2718,14,202127180014,202127180014-Augusto Coutinho,26-Transporte / 782-Transporte Rodoviário,0465.4134.A170,NaN,0,500000,5
16,20190,Enviado para Análise,Sim,2023-03-29T00:00:00,2026-03-29T00:00:00,36,16630,PROGRAMA DE TRABALHO 12.571.0069.4739.2998 - P...,False,False,...,2885,20,202228850020,202228850020-Humberto Costa,"12-Educação / 364-Ensino Superior , 13-Cultura...",12.571.0069.4739.2998,NaN,150000,350000,7
17,20640,Enviado para Análise,Sim,2021-09-24T00:00:00,2024-09-24T00:00:00,36,11064,26.782.0465.A170,False,False,...,3387,2,202133870002,202133870002-Wolney Queiroz,26-Transporte / 782-Transporte Rodoviário,26.782.04565.4134.A170,NaN,0,2000000,5
18,21165,Enviado para Análise,Sim,2022-07-01T00:00:00,2024-07-01T00:00:00,24,15962,13.391.0929.4724,False,False,...,1690,3,202216900003,202216900003-Renildo Calheiros,"13-Cultura / 391-Patrimônio Histórico, Artísti...",13.391.0929.4724,NaN,0,352000,7
19,20984,Enviado para Análise,Não,2023-08-30T00:00:00,2026-08-30T00:00:00,36,36482,NaN,False,False,...,3767,7,202337670007,202337670007-Tadeu Alencar,8-Assistência Social / 243-Assistência à Crian...,1161- Estruturação da rede SUAS no Estado de P...,NaN,0,100000,12